feat: Build macOS
Squad-Maker/squad-maker-backend pull request #1
Opened 2024-10-30 12:31 UTC by MarcusToledo

- Alterado Makefile para builder de acordo com OS
- Criado comando de build para macOS
- Criado .env.example
-  Atualizado dependências do projeto

2024-10-30 12:38 UTC, pedrokarnoski approved these changes

2024-10-30 22:27 UTC, Hellysonrp requested changes

2024-10-30 22:27 UTC, Hellysonrp commented on Makefile
> +build-win:
remove esse tab perdido aí

2024-10-31 00:31 UTC, MarcusToledo commented on Makefile
> +build-win:
Ajustado

2024-10-31 00:35 UTC, Hellysonrp approved these changes

2024-10-31 00:36 UTC, merged